version: '3.8'

services:
  mlflow:
    image: mlflow-container
    container_name: mlflow-server
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    volumes:
      - ./mlflow/mlflow_data:/app/mlruns  
      - ./mlflow/mlflow_db:/app/mlflow.db  
    networks:
      - ml_network

  # fastapi:
  #   image: fastapi-container
  #   container_name: fastapi-server
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mlflow
  #     - train
  #   environment:
  #     - MLFLOW_TRACKING_URI=http://mlflow:5001
  #   networks:
  #     - ml_network

  # train:
    # image: train-container
    # container_name: train-server
    # depends_on:
    #   - mlflow
    # environment:
    #   - MLFLOW_TRACKING_URI=http://mlflow:5001
    # networks:
    #   - ml_network

networks:
  ml_network:
    driver: bridge